receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 2s
    send_batch_size: 100

  resource:
    attributes:
      - key: app
        value: ecommerce-backend
        action: upsert
      - key: environment
        value: production
        action: upsert

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push   # "loki" = docker-compose service name
    labels:
      resource:
        app:         "app"
        environment: "environment"
      attributes:
        alert_type:        "alert_type"
        severity:          "severity"
        service:           "service"
        log_owner:         "log_owner"
        status_code:       "status_code"
        resolution_status: "resolution_status"
        source:            "source"

  debug:
    verbosity: basic

service:
  pipelines:
    logs:
      receivers:  [otlp]
      processors: [resource, batch]
      exporters:  [loki, debug]
